import React from 'react';
import type { Metadata } from 'next';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import Breadcrumbs from '@/components/Breadcrumbs';
import FAQClient from '@/components/FAQ';

export const metadata: Metadata = {
  title: 'FAQ | Cee Writing Hub — Common Questions Answered',
  description: 'Answers to every question about our writing, plagiarism check, CV, SOP, and research services. Delivery time, confidentiality, revisions, AI humanizing, pricing — all explained.',
  alternates: { canonical: '/faq' },
  openGraph: {
    title: 'Frequently Asked Questions | Cee Writing Hub',
    description: 'Everything you need to know before placing an order. Delivery time, confidentiality, revisions, and more.',
    type: 'website',
  },
  robots: { index: true, follow: true, googleBot: { index: true, follow: true, 'max-snippet': -1 } },
};

const ALL_FAQS = [
  {
    category: 'Plagiarism & Turnitin',
    items: [
      { q: 'Is your Turnitin access real? Can I trust the report?', a: 'Yes. We use a legitimate institutional Turnitin account — not a free or cracked version. The report we send you is an official PDF directly from Turnitin, including your full similarity score, AI detection percentage, and a complete source breakdown. It is the same report your university would see.' },
      { q: 'What is the difference between similarity score and AI detection?', a: 'Similarity score measures how much of your text matches other published sources (plagiarism). AI detection measures how much of your text was likely generated by an AI tool like ChatGPT. These are two separate scores on the Turnitin report. We check both.' },
      { q: 'Can you reduce both my plagiarism AND AI score?', a: 'Yes — this is one of our most requested services. We restructure arguments, rephrase sentences at the root level, and humanise the writing so that both the similarity score and AI detection score drop significantly while keeping the academic integrity intact.' },
    ],
  },
  {
    category: 'Delivery & Process',
    items: [
      { q: 'How long does an order take?', a: 'Plagiarism checks: 1–4 hours. Proofreading and short edits: 12–24 hours. Full CV or SOP writing: 24–48 hours. Research proposals or thesis chapters: 2–4 days. Same-day delivery is available for most services — just let us know your deadline when you message us.' },
      { q: 'Can you handle urgent same-day orders?', a: 'Yes. For plagiarism checks, proofreading, and short documents, same-day turnaround is standard. For larger documents, we can often accommodate 12-hour deadlines with an urgency fee. Always state your deadline at the start and we will be honest about what is possible.' },
      { q: 'How do I place an order?', a: 'Click the WhatsApp button, tell us the service you need, share your document (if applicable), and we will send you a price and estimated delivery time. Payment is confirmed before we begin. That\'s it — no forms, no logins, no waiting in a queue.' },
    ],
  },
  {
    category: 'Confidentiality & Trust',
    items: [
      { q: 'Is my document kept confidential?', a: 'Absolutely. We operate under strict confidentiality. We never share, publish, reuse, or distribute your documents to any third party — ever. Your work is only seen by the team member handling your order. Files are permanently deleted after delivery unless you ask us to keep them.' },
      { q: 'Do you use AI to write my document?', a: 'No. All work is 100% human-written by our team of qualified writers and researchers. We use tools like SPSS, Stata, R, and Python for data analysis, but the writing, interpretation, and argumentation are done by trained humans. We reject and rework any AI-generated content.' },
      { q: 'What if I am not happy with the result?', a: 'We offer unlimited free revisions until you are genuinely satisfied. If we cannot meet your stated requirements after multiple revision rounds, we will issue a partial or full refund depending on the situation. Your satisfaction is not a policy — it is our actual standard.' },
    ],
  },
  {
    category: 'Services & Pricing',
    items: [
      { q: 'How much do your services cost?', a: 'Pricing varies by service and document length. Plagiarism checks start from ₦3,000. CV writing starts from ₦15,000. SOP and research writing are priced per page or by project scope. Message us on WhatsApp with your document and we will give you an exact quote within minutes.' },
      { q: 'Do you work with clients outside Nigeria?', a: 'Yes. We serve clients in the UK, USA, Canada, Australia, UAE, and across the diaspora. We accept international payment methods and deliver everything digitally. Time zone differences are never an issue — we operate around the clock.' },
      { q: 'What types of documents can you handle?', a: 'Undergraduate and postgraduate essays, theses, dissertations, literature reviews, research proposals, SOPs, CVs, cover letters, business plans, journal articles, data analysis (SPSS, STATA, R, Python, NVivo, EViews), and scholarship application documents.' },
    ],
  },
  {
    category: 'Scholarships & Academic Prep',
    items: [
      { q: 'Can you help me write a winning scholarship application?', a: 'Yes. We have helped applicants secure Chevening, DAAD, Erasmus Mundus, and Commonwealth scholarships. We write SOPs, personal statements, and research proposals that are tailored to the specific scholarship\'s selection criteria — not generic templates.' },
      { q: 'What is the Scholarship Readiness Checker?', a: 'It is our free tool that evaluates your profile against the actual selection criteria used by DAAD, Chevening, Erasmus, and Fulbright. It takes under 15 minutes and gives you a personalised score plus a 30/60/90-day action plan. No email required. Try it at ceewriting.com/scholarship-check.' },
    ],
  },
];

const faqJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: ALL_FAQS.flatMap(c => c.items).map(({ q, a }) => ({
    '@type': 'Question',
    name: q,
    acceptedAnswer: { '@type': 'Answer', text: a },
  })),
};

export default function FAQPage() {
  return (
    <main style={{ backgroundColor: '#0A0A0A', minHeight: '100vh' }}>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />
      <Navbar />

      {/* Hero */}
      <section
        style={{
          paddingTop: '160px',
          paddingBottom: '80px',
          paddingLeft: 'clamp(24px, 6vw, 100px)',
          paddingRight: 'clamp(24px, 6vw, 100px)',
          borderBottom: '1px solid rgba(197,160,89,0.1)',
          maxWidth: '1280px',
          margin: '0 auto',
        }}
      >
        <Breadcrumbs items={[{ label: 'Home', href: '/' }, { label: 'FAQ', href: '/faq' }]} />
        <p
          className="font-space"
          style={{
            fontSize: '11px', fontWeight: 700, letterSpacing: '0.25em', textTransform: 'uppercase',
            color: 'rgba(197,160,89,0.6)', marginBottom: '32px',
          }}
        >
          Help Center
        </p>
        <h1
          className="font-space"
          style={{
            fontSize: 'clamp(40px, 7vw, 88px)', fontWeight: 700, lineHeight: 1.04,
            letterSpacing: '-0.02em', color: '#EAEAEA', marginBottom: '32px',
          }}
        >
          Got <span style={{ color: '#C5A059' }}>Questions?</span><br />We have answers.
        </h1>
        <p
          className="font-inter"
          style={{
            fontSize: '18px', lineHeight: 1.8, color: '#888888', fontWeight: 300,
            maxWidth: '560px',
          }}
        >
          Everything you need to know before placing your order. Can't find what you're looking for? Message us on WhatsApp — we reply in minutes.
        </p>
      </section>

      {/* FAQ content */}
      <FAQClient faqs={ALL_FAQS} />

      {/* Bottom CTA */}
      <section
        style={{
          backgroundColor: '#111111',
          borderTop: '1px solid rgba(197,160,89,0.1)',
          paddingTop: '100px',
          paddingBottom: '100px',
          paddingLeft: 'clamp(24px, 6vw, 100px)',
          paddingRight: 'clamp(24px, 6vw, 100px)',
        }}
      >
        <div style={{ maxWidth: '1280px', margin: '0 auto' }}>
          <div style={{ display: 'flex', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: '48px' }}>
            <div style={{ flex: '1 1 400px' }}>
              <p className="font-space" style={{ fontSize: '11px', fontWeight: 700, letterSpacing: '0.25em', textTransform: 'uppercase', color: 'rgba(197,160,89,0.6)', marginBottom: '24px' }}>
                Still Need Help?
              </p>
              <h2
                className="font-space"
                style={{ fontSize: 'clamp(28px, 4vw, 52px)', fontWeight: 700, lineHeight: 1.1, letterSpacing: '-0.02em', color: '#EAEAEA', marginBottom: '16px' }}
              >
                Talk to us directly.<br />We reply in <span style={{ color: '#C5A059' }}>under 2 minutes.</span>
              </h2>
              <p className="font-inter" style={{ fontSize: '17px', lineHeight: 1.8, color: '#888888', fontWeight: 300 }}>
                Our team is online and ready. No bots, no ticket queues — just a real person who knows the answer.
              </p>
            </div>
            <div style={{ flex: '0 1 auto', display: 'flex', flexDirection: 'column', gap: '16px' }}>
              <a
                href="https://wa.me/2349056752549" target="_blank" rel="noreferrer"
                className="font-space"
                style={{
                  display: 'inline-flex', alignItems: 'center', gap: '12px',
                  padding: '20px 40px', backgroundColor: '#C5A059', color: '#0A0A0A',
                  fontSize: '13px', fontWeight: 700, letterSpacing: '0.15em', textTransform: 'uppercase',
                  textDecoration: 'none',
                }}
              >
                WhatsApp Us Now
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                  <line x1="5" y1="12" x2="19" y2="12" />
                  <polyline points="12 5 19 12 12 19" />
                </svg>
              </a>
              <p className="font-space" style={{ fontSize: '10px', fontWeight: 700, letterSpacing: '0.15em', textTransform: 'uppercase', color: '#555555', textAlign: 'center' }}>
                Free. No obligation.
              </p>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </main>
  );
}
