const fs = require('fs');

let terms = JSON.parse(fs.readFileSync('temp.json', 'utf8'));

// Load all generated outputs
let allNewTerms = {};
for (let i = 0; i <= 5; i++) {
  try {
    let data = JSON.parse(fs.readFileSync(`out_${i}.json`, 'utf8'));
    Object.assign(allNewTerms, data);
  } catch (e) {
    console.error(`Error reading out_${i}.json:`, e);
  }
}

let modifiedCount = 0;
terms = terms.map(t => {
  if (allNewTerms[t.slug]) {
    modifiedCount++;
    // Keep original term, slug, category, relatedTools, relatedServices (if they exist)
    // but update the content fields generated by the LLM.
    const newContent = allNewTerms[t.slug];
    
    // Some subagents might not have included relatedTools or relatedServices. Keep the original empty arrays or existing ones.
    const merged = {
      ...t,
      shortDefinition: newContent.shortDefinition,
      definition: newContent.definition,
      whyItMatters: newContent.whyItMatters,
      example: newContent.example,
      interpretation: newContent.interpretation || "",
      commonMistakes: newContent.commonMistakes || []
    };
    return merged;
  }
  return t;
});

const newContent = [
  "export interface GlossaryTerm {",
  "  slug: string;",
  "  term: string;",
  "  category: string;",
  "  shortDefinition: string;",
  "  definition: string;",
  "  whyItMatters: string;",
  "  example: string;",
  "  interpretation?: string;",
  "  commonMistakes?: string[];",
  "  relatedTerms?: string[];",
  "  relatedArticles?: string[];",
  "  relatedTools?: string[];",
  "  relatedServices?: string[];",
  "}",
  "",
  `export const glossaryData: GlossaryTerm[] = ${JSON.stringify(terms, null, 2)};`
].join('\n');

fs.writeFileSync('src/features/research/data/glossary.ts', newContent, 'utf8');
console.log(`Updated ${modifiedCount} terms with new generated definitions.`);
