/* ============================================================
   Scholarship Readiness Checker — Question Banks
   ============================================================ */

import type { TrackId, QuestionSection } from './types';

// ── Helmut-Schmidt Track ──
const HELMUT_SCHMIDT_QUESTIONS: QuestionSection[] = [
  {
    id: 'hs-eligibility',
    title: 'Eligibility',
    estimatedMinutes: 2,
    questions: [
      {
        id: 'hs-gate-1',
        type: 'gate',
        text: 'Are you a citizen of a DAAD-eligible developing country (DAC list)?',
        section: 'eligibility',
        sectionIndex: 0,
        helpText: 'The Helmut-Schmidt Programme is for professionals from developing countries listed on the OECD DAC list.',
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
        ],
        gateFailMessage: 'The Helmut-Schmidt Programme is only open to citizens of DAAD-eligible developing countries. You may want to consider Erasmus Mundus, which has broader eligibility.',
        gateRecommendedTrack: 'erasmus',
        required: true,
      },
      {
        id: 'hs-gate-2',
        type: 'gate',
        text: 'Is your degree in a field related to governance, public policy, law, economics, or public administration?',
        section: 'eligibility',
        sectionIndex: 0,
        helpText: 'This programme targets social sciences and governance-related disciplines.',
        options: [
          { value: 'yes', label: 'Yes — directly related' },
          { value: 'partial', label: 'Partially — my work is related but degree is in another field' },
          { value: 'no', label: 'No — different field entirely' },
        ],
        gateFailMessage: 'Helmut-Schmidt is specifically for governance, public policy, law, economics, and administration fields. Consider EPOS for broader development-related disciplines.',
        gateRecommendedTrack: 'epos',
        required: true,
      },
      {
        id: 'hs-gate-3',
        type: 'gate',
        text: 'Do you have professional experience (including internships, volunteering, or part-time work)?',
        section: 'eligibility',
        sectionIndex: 0,
        helpText: 'Helmut-Schmidt accepts internships, volunteering, and part-time work as valid experience — unlike EPOS which requires paid work only.',
        options: [
          { value: 'yes', label: 'Yes — I have work experience' },
          { value: 'no', label: 'No — I have no experience at all' },
        ],
        gateFailMessage: 'Some form of professional experience is expected. Even internships and volunteering count for Helmut-Schmidt.',
        required: true,
      },
      {
        id: 'hs-gate-4',
        type: 'gate',
        text: 'Are you currently living in Germany?',
        section: 'eligibility',
        sectionIndex: 0,
        helpText: 'Applicants already residing in Germany at the time of application are not eligible.',
        options: [
          { value: 'no', label: 'No — I do not live in Germany' },
          { value: 'yes', label: 'Yes — I currently live in Germany' },
        ],
        gateFailMessage: 'Applicants who are already living in Germany at the time of application are not eligible for the Helmut-Schmidt Programme.',
        required: true,
      },
    ],
  },
  {
    id: 'hs-academic',
    title: 'Academic Readiness',
    estimatedMinutes: 3,
    questions: [
      {
        id: 'hs-acad-1',
        type: 'number',
        text: 'What is your GPA? (Enter the value on your transcript)',
        section: 'academic',
        sectionIndex: 1,
        helpText: 'Enter your GPA as shown on your transcript. We will convert it using your scale from onboarding.',
        required: true,
      },
      {
        id: 'hs-acad-2',
        type: 'gate',
        text: 'Have you identified partner universities offering Helmut-Schmidt-eligible programmes?',
        section: 'academic',
        sectionIndex: 1,
        helpText: 'You need to apply to a specific partner university programme. Check the DAAD website for the list.',
        options: [
          { value: 'yes', label: 'Yes — I have identified specific programmes' },
          { value: 'some', label: 'I have started researching but not finalised' },
          { value: 'no', label: 'No — I have not started looking' },
        ],
        required: true,
      },
      {
        id: 'hs-acad-3',
        type: 'objective',
        text: 'Is your field of study directly connected to your current or most recent work?',
        section: 'academic',
        sectionIndex: 1,
        helpText: 'DAAD values a clear link between your professional background and your chosen field of study.',
        options: [
          { value: 'strong', label: 'Yes — my work and study field are clearly connected' },
          { value: 'moderate', label: 'Somewhat — there is some overlap' },
          { value: 'weak', label: 'No — they are in different areas' },
        ],
        required: true,
      },
    ],
  },
  {
    id: 'hs-language',
    title: 'Language Readiness',
    estimatedMinutes: 2,
    questions: [
      {
        id: 'hs-lang-1',
        type: 'select',
        text: 'What English language certificate do you have (or are preparing for)?',
        section: 'language',
        sectionIndex: 2,
        helpText: 'Most Helmut-Schmidt programmes are taught in English. Check your chosen programme\'s specific requirements.',
        options: [
          { value: 'ielts-7+', label: 'IELTS 7.0 or above' },
          { value: 'ielts-6.5', label: 'IELTS 6.5' },
          { value: 'ielts-6', label: 'IELTS 6.0' },
          { value: 'toefl-100+', label: 'TOEFL 100+' },
          { value: 'toefl-90', label: 'TOEFL 90–99' },
          { value: 'toefl-80', label: 'TOEFL 80–89' },
          { value: 'none', label: 'No certificate yet' },
        ],
        required: true,
      },
      {
        id: 'hs-lang-2',
        type: 'objective',
        text: 'Have you confirmed that your chosen programme is taught in English (or that you meet the language of instruction requirements)?',
        section: 'language',
        sectionIndex: 2,
        helpText: 'Some programmes may require German. Confirm the language of instruction with your chosen university.',
        options: [
          { value: 'confirmed', label: 'Yes — confirmed English medium' },
          { value: 'checking', label: 'Still checking' },
          { value: 'german', label: 'Programme requires German' },
        ],
        required: true,
      },
    ],
  },
  {
    id: 'hs-motivation',
    title: 'Development Motivation',
    estimatedMinutes: 8,
    questions: [
      {
        id: 'hs-mot-1',
        type: 'self-score-text',
        text: 'Describe a specific development challenge in your country or region that you are passionate about addressing. How have you contributed to tackling this challenge so far?',
        section: 'motivation',
        sectionIndex: 3,
        helpText: 'Be specific: name the challenge, your role, and measurable outcomes where possible. Avoid generic statements.',
        minWords: 80,
        maxWords: 300,
        required: true,
      },
      {
        id: 'hs-mot-2',
        type: 'self-score-text',
        text: 'Describe your concrete plan for returning to your home country after your studies. What specific position, project, or initiative will you pursue?',
        section: 'motivation',
        sectionIndex: 3,
        helpText: 'DAAD wants to see a clear, realistic return plan — not vague ambitions. Mention specific organisations, roles, or projects.',
        minWords: 80,
        maxWords: 300,
        required: true,
      },
    ],
  },
  {
    id: 'hs-programme',
    title: 'Programme Connection',
    estimatedMinutes: 5,
    questions: [
      {
        id: 'hs-prog-1',
        type: 'self-score-text',
        text: 'How does your current professional work connect to your chosen field of study? Why is this specific programme necessary for your career goals?',
        section: 'programme',
        sectionIndex: 4,
        helpText: 'Show the selection committee why your work experience makes you a strong candidate for this specific programme.',
        minWords: 80,
        maxWords: 300,
        required: true,
      },
    ],
  },
  {
    id: 'hs-documents',
    title: 'Document Readiness',
    estimatedMinutes: 2,
    questions: [
      {
        id: 'hs-doc-1',
        type: 'checklist',
        text: 'Which of the following documents do you have ready?',
        section: 'documents',
        sectionIndex: 5,
        helpText: 'Tick all documents you have already prepared. Missing documents will appear in your action plan.',
        checklistItems: [
          'CV in Europass format',
          'Academic transcripts (certified copies)',
          'Two reference letters from professional or academic referees',
          'Valid passport (at least 18 months validity)',
          'Proof of professional experience (letters, contracts, or certificates)',
        ],
        required: true,
      },
    ],
  },
];

// ── EPOS Track ──
const EPOS_QUESTIONS: QuestionSection[] = [
  {
    id: 'epos-eligibility',
    title: 'Eligibility',
    estimatedMinutes: 2,
    questions: [
      {
        id: 'epos-gate-1',
        type: 'gate',
        text: 'Are you a citizen of a DAAD-eligible developing country?',
        section: 'eligibility',
        sectionIndex: 0,
        helpText: 'EPOS is open to professionals from developing countries on the OECD DAC list.',
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
        ],
        gateFailMessage: 'EPOS is only open to citizens of DAAD-eligible developing countries. Consider Erasmus Mundus for broader eligibility.',
        gateRecommendedTrack: 'erasmus',
        required: true,
      },
      {
        id: 'epos-gate-2',
        type: 'gate',
        text: 'Do you have at least 2 years of PAID professional experience? (Internships, volunteering, part-time, and academic work do NOT count)',
        section: 'eligibility',
        sectionIndex: 0,
        helpText: 'EPOS is strict: only full-time paid employment counts. Internships, volunteering, part-time, and academic positions are excluded. This is the #1 reason applicants are rejected.',
        options: [
          { value: 'yes', label: 'Yes — 2+ years of paid full-time work' },
          { value: 'no', label: 'No — I don\'t meet this requirement' },
        ],
        gateFailMessage: 'EPOS strictly requires 2 years of paid professional experience (excluding internships, volunteering, part-time, and academic work). Consider Helmut-Schmidt, which accepts internships and volunteering.',
        gateRecommendedTrack: 'helmut-schmidt',
        required: true,
      },
      {
        id: 'epos-gate-3',
        type: 'gate',
        text: 'Did you complete your last degree within the past 6 years?',
        section: 'eligibility',
        sectionIndex: 0,
        helpText: 'EPOS generally requires that your degree is not older than 6 years at the time of application.',
        options: [
          { value: 'yes', label: 'Yes — within the last 6 years' },
          { value: 'no', label: 'No — my degree is older than 6 years' },
        ],
        gateFailMessage: 'EPOS generally requires your degree to be under 6 years old. Some programmes may have exceptions — check individual course requirements.',
        required: true,
      },
      {
        id: 'epos-gate-4',
        type: 'gate',
        text: 'Are you currently living in Germany?',
        section: 'eligibility',
        sectionIndex: 0,
        helpText: 'Applicants already residing in Germany are generally not eligible.',
        options: [
          { value: 'no', label: 'No — I do not live in Germany' },
          { value: 'yes', label: 'Yes — I currently live in Germany' },
        ],
        gateFailMessage: 'Applicants already living in Germany at the time of application are typically not eligible for EPOS.',
        required: true,
      },
    ],
  },
  {
    id: 'epos-experience',
    title: 'Experience Quality',
    estimatedMinutes: 3,
    questions: [
      {
        id: 'epos-exp-1',
        type: 'select',
        text: 'What sector is your current or most recent employer in?',
        section: 'experience',
        sectionIndex: 1,
        helpText: 'EPOS values experience in development-relevant sectors.',
        options: [
          { value: 'government', label: 'Government / Public sector' },
          { value: 'ngo', label: 'NGO / International organisation' },
          { value: 'private-dev', label: 'Private sector (development-related)' },
          { value: 'private-other', label: 'Private sector (not development-related)' },
          { value: 'academic', label: 'Academic / Research institution' },
          { value: 'other', label: 'Other' },
        ],
        required: true,
      },
      {
        id: 'epos-exp-2',
        type: 'objective',
        text: 'Is your current work directly related to development (poverty reduction, health, education, environment, governance, infrastructure)?',
        section: 'experience',
        sectionIndex: 1,
        helpText: 'EPOS is a development-focused programme. The connection between your work and development goals matters.',
        options: [
          { value: 'direct', label: 'Yes — directly related to development' },
          { value: 'indirect', label: 'Somewhat — indirectly related' },
          { value: 'no', label: 'No — not related to development' },
        ],
        required: true,
      },
      {
        id: 'epos-exp-3',
        type: 'objective',
        text: 'Do you have official work certificates on headed paper with dates, signature, and stamp from your employer(s)?',
        section: 'experience',
        sectionIndex: 1,
        helpText: 'EPOS requires formal work certificates — not just reference letters. These must be on official letterhead with dates of employment, employer signature, and company stamp.',
        options: [
          { value: 'all', label: 'Yes — I have official certificates for all positions' },
          { value: 'some', label: 'I have certificates for some positions' },
          { value: 'none', label: 'No — I only have informal references' },
        ],
        required: true,
      },
    ],
  },
  {
    id: 'epos-academic',
    title: 'Academic Background',
    estimatedMinutes: 2,
    questions: [
      {
        id: 'epos-acad-1',
        type: 'objective',
        text: 'What is your degree classification or GPA standing?',
        section: 'academic',
        sectionIndex: 2,
        helpText: 'EPOS expects applicants to have graduated in the upper third of their class. First Class / 2:1 / GPA ≥ 3.5 (5.0 scale) is competitive.',
        options: [
          { value: 'first', label: 'First Class / Distinction' },
          { value: '2-1', label: 'Second Class Upper (2:1)' },
          { value: '2-2', label: 'Second Class Lower (2:2)' },
          { value: 'third', label: 'Third Class or below' },
        ],
        required: true,
      },
      {
        id: 'epos-acad-2',
        type: 'objective',
        text: 'Is your Bachelor\'s degree a 4-year programme (or equivalent)?',
        section: 'academic',
        sectionIndex: 2,
        helpText: 'German universities typically require a 4-year Bachelor\'s for Masters admission. 3-year degrees may need a bridging programme.',
        options: [
          { value: 'yes', label: 'Yes — 4 years or more' },
          { value: 'no', label: 'No — 3 years' },
          { value: 'unsure', label: 'Not sure' },
        ],
        required: true,
      },
    ],
  },
  {
    id: 'epos-motivation',
    title: 'Development Motivation',
    estimatedMinutes: 8,
    questions: [
      {
        id: 'epos-mot-1',
        type: 'self-score-text',
        text: 'How does your current work contribute to the development of your country or region? Provide specific examples of your impact.',
        section: 'motivation',
        sectionIndex: 3,
        helpText: 'Be concrete: what projects have you worked on? What measurable change have you contributed to? Avoid generic statements about "wanting to help".',
        minWords: 80,
        maxWords: 300,
        required: true,
      },
      {
        id: 'epos-mot-2',
        type: 'self-score-text',
        text: 'What specific change do you plan to drive after completing your studies? Describe the project, initiative, or role you will pursue upon return.',
        section: 'motivation',
        sectionIndex: 3,
        helpText: 'DAAD evaluators look for a concrete, realistic post-study plan — not vague aspirations. Name specific organisations, roles, or initiatives.',
        minWords: 80,
        maxWords: 300,
        required: true,
      },
    ],
  },
  {
    id: 'epos-courses',
    title: 'Course Selection',
    estimatedMinutes: 3,
    questions: [
      {
        id: 'epos-course-1',
        type: 'objective',
        text: 'Have you reviewed the official EPOS course list on the DAAD website?',
        section: 'programme',
        sectionIndex: 4,
        helpText: 'You can ONLY apply to courses specifically listed as EPOS-eligible. Not all German Masters programmes qualify.',
        options: [
          { value: 'yes', label: 'Yes — I have reviewed the list' },
          { value: 'no', label: 'No — I haven\'t seen it yet' },
        ],
        required: true,
      },
      {
        id: 'epos-course-2',
        type: 'objective',
        text: 'How many EPOS-eligible courses have you identified as matching your profile?',
        section: 'programme',
        sectionIndex: 4,
        helpText: 'You can apply to up to 3 courses. Having at least 2 strong choices increases your chances.',
        options: [
          { value: '3+', label: '3 or more courses identified' },
          { value: '1-2', label: '1–2 courses identified' },
          { value: '0', label: 'None yet' },
        ],
        required: true,
      },
      {
        id: 'epos-course-3',
        type: 'objective',
        text: 'Have you checked the specific application deadlines for your chosen courses?',
        section: 'programme',
        sectionIndex: 4,
        helpText: 'EPOS deadlines vary per course and are often earlier than you expect. Some close as early as September for the following year.',
        options: [
          { value: 'yes', label: 'Yes — I know my deadlines' },
          { value: 'no', label: 'No — I need to check' },
        ],
        required: true,
      },
    ],
  },
  {
    id: 'epos-documents',
    title: 'Document Readiness',
    estimatedMinutes: 2,
    questions: [
      {
        id: 'epos-doc-1',
        type: 'checklist',
        text: 'Which of the following documents do you have ready?',
        section: 'documents',
        sectionIndex: 5,
        helpText: 'EPOS has strict document requirements. Missing or improperly formatted documents are a common rejection reason.',
        checklistItems: [
          'Europass CV in reverse chronological order',
          'Work certificates on official letterhead with dates, signature, and stamp',
          'Certified translations of all non-English documents',
          'IELTS 6.0+ (or equivalent English certificate)',
          'Academic transcripts (certified)',
          'Degree certificate (certified)',
        ],
        required: true,
      },
    ],
  },
];

// ── Erasmus Mundus Track ──
const ERASMUS_QUESTIONS: QuestionSection[] = [
  {
    id: 'erasmus-eligibility',
    title: 'Eligibility',
    estimatedMinutes: 2,
    questions: [
      {
        id: 'erasmus-gate-1',
        type: 'gate',
        text: 'Do you hold a Bachelor\'s degree (or will you complete one before the programme starts)?',
        section: 'eligibility',
        sectionIndex: 0,
        helpText: 'A completed Bachelor\'s degree is required for Erasmus Mundus Joint Masters.',
        options: [
          { value: 'yes', label: 'Yes — completed or will complete in time' },
          { value: 'no', label: 'No' },
        ],
        gateFailMessage: 'A Bachelor\'s degree is required for Erasmus Mundus Joint Master programmes.',
        required: true,
      },
      {
        id: 'erasmus-gate-2',
        type: 'gate',
        text: 'Have you previously received an Erasmus Mundus scholarship?',
        section: 'eligibility',
        sectionIndex: 0,
        helpText: 'You cannot receive an Erasmus Mundus scholarship more than once.',
        options: [
          { value: 'no', label: 'No — this would be my first' },
          { value: 'yes', label: 'Yes — I have received one before' },
        ],
        gateFailMessage: 'Erasmus Mundus scholarships are awarded only once per person. Consider DAAD, Chevening, or Fulbright instead.',
        gateRecommendedTrack: 'chevening',
        required: true,
      },
      {
        id: 'erasmus-elig-3',
        type: 'objective',
        text: 'Have you been living in an EU country for more than 12 months in the past 3 years?',
        section: 'residency',
        sectionIndex: 0,
        helpText: 'This is NOT a disqualifier. If you have lived in the EU for 12+ months, you are categorised as a "Programme Country" applicant instead of "Partner Country". Partner Country applicants receive a higher scholarship amount (€1,400/month vs €1,000/month).',
        options: [
          { value: 'no', label: 'No — I qualify as Partner Country (higher scholarship)' },
          { value: 'yes', label: 'Yes — I would be a Programme Country applicant' },
          { value: 'unsure', label: 'I\'m not sure' },
        ],
        required: true,
      },
    ],
  },
  {
    id: 'erasmus-programme',
    title: 'Programme Selection',
    estimatedMinutes: 4,
    questions: [
      {
        id: 'erasmus-prog-1',
        type: 'objective',
        text: 'Have you identified specific Erasmus Mundus Joint Master programmes to apply to?',
        section: 'programme',
        sectionIndex: 1,
        helpText: 'Erasmus Mundus is NOT one scholarship — it\'s hundreds of individual programmes, each with their own requirements and deadlines.',
        options: [
          { value: 'yes', label: 'Yes — I have specific programmes in mind' },
          { value: 'browsing', label: 'I\'m still browsing the catalogue' },
          { value: 'no', label: 'No — I haven\'t started' },
        ],
        required: true,
      },
      {
        id: 'erasmus-prog-2',
        type: 'select',
        text: 'How many programmes have you shortlisted?',
        section: 'programme',
        sectionIndex: 1,
        helpText: 'Applying to 3–5 programmes is a good strategy. Each requires a tailored motivation letter.',
        options: [
          { value: '5+', label: '5 or more' },
          { value: '3-4', label: '3–4 programmes' },
          { value: '1-2', label: '1–2 programmes' },
          { value: '0', label: 'None yet' },
        ],
        required: true,
      },
      {
        id: 'erasmus-prog-3',
        type: 'objective',
        text: 'Have you verified the application deadlines for your shortlisted programmes?',
        section: 'programme',
        sectionIndex: 1,
        helpText: 'Deadlines vary widely — some close in October, others in January. Missing a deadline means waiting another full year.',
        options: [
          { value: 'yes', label: 'Yes — I have all deadlines noted' },
          { value: 'some', label: 'I have some deadlines but not all' },
          { value: 'no', label: 'No — I haven\'t checked deadlines yet' },
        ],
        required: true,
      },
      {
        id: 'erasmus-prog-4',
        type: 'objective',
        text: 'Is your degree field related to the programmes you are applying to?',
        section: 'programme',
        sectionIndex: 1,
        helpText: 'Most programmes require a related undergraduate degree. Some interdisciplinary programmes are more flexible.',
        options: [
          { value: 'direct', label: 'Directly related' },
          { value: 'related', label: 'Related / overlapping field' },
          { value: 'different', label: 'Different field' },
        ],
        required: true,
      },
    ],
  },
  {
    id: 'erasmus-academic',
    title: 'Academic Readiness',
    estimatedMinutes: 2,
    questions: [
      {
        id: 'erasmus-acad-1',
        type: 'objective',
        text: 'What is your degree classification or GPA standing?',
        section: 'academic',
        sectionIndex: 2,
        helpText: 'Competitive Erasmus applicants typically have a strong academic record, though requirements vary by programme.',
        options: [
          { value: 'first', label: 'First Class / Distinction / GPA 3.5+' },
          { value: '2-1', label: 'Second Class Upper (2:1) / GPA 3.0–3.49' },
          { value: '2-2', label: 'Second Class Lower (2:2) / GPA 2.5–2.99' },
          { value: 'third', label: 'Third Class or below' },
        ],
        required: true,
      },
      {
        id: 'erasmus-acad-2',
        type: 'objective',
        text: 'Do you have any academic awards, publications, conference presentations, or research experience?',
        section: 'academic',
        sectionIndex: 2,
        helpText: 'These strengthen your application but are not always required. Mention any in your motivation letter.',
        options: [
          { value: 'multiple', label: 'Yes — publications, awards, or conference presentations' },
          { value: 'some', label: 'Some research experience or minor awards' },
          { value: 'none', label: 'No' },
        ],
        required: true,
      },
    ],
  },
  {
    id: 'erasmus-motivation',
    title: 'Motivation',
    estimatedMinutes: 8,
    questions: [
      {
        id: 'erasmus-mot-1',
        type: 'self-score-text',
        text: 'Why this specific Erasmus Mundus programme? Reference specific elements of the programme (modules, partner universities, unique features) that attract you.',
        section: 'motivation',
        sectionIndex: 3,
        helpText: 'The motivation letter is the PRIMARY selector for Erasmus Mundus. Generic motivations are rejected. Reference specific courses, professors, research centres, or unique aspects of the programme.',
        minWords: 80,
        maxWords: 300,
        required: true,
      },
      {
        id: 'erasmus-mot-2',
        type: 'self-score-text',
        text: 'How will this programme advance your career goals? What specific impact do you expect it to have on your professional development?',
        section: 'motivation',
        sectionIndex: 3,
        helpText: 'Connect the programme\'s offerings to your concrete career objectives. Show a clear before→during→after narrative.',
        minWords: 80,
        maxWords: 300,
        required: true,
      },
    ],
  },
  {
    id: 'erasmus-language',
    title: 'Language Readiness',
    estimatedMinutes: 2,
    questions: [
      {
        id: 'erasmus-lang-1',
        type: 'select',
        text: 'What is your English language certification status?',
        section: 'language',
        sectionIndex: 4,
        helpText: 'Most Erasmus Mundus programmes require IELTS 6.5+ or TOEFL 90+. Check your specific programme\'s requirements.',
        options: [
          { value: 'ielts-7+', label: 'IELTS 7.0+ / TOEFL 100+' },
          { value: 'ielts-6.5', label: 'IELTS 6.5 / TOEFL 90–99' },
          { value: 'ielts-6', label: 'IELTS 6.0 / TOEFL 80–89' },
          { value: 'below', label: 'Below IELTS 6.0 / TOEFL 80' },
          { value: 'none', label: 'No certificate yet' },
        ],
        required: true,
      },
      {
        id: 'erasmus-lang-2',
        type: 'objective',
        text: 'Have you checked if your chosen programmes have additional local language requirements (e.g., French, Spanish, Italian)?',
        section: 'language',
        sectionIndex: 4,
        helpText: 'Since you study in 2–3 countries, some programmes require or recommend local language skills for certain semesters.',
        options: [
          { value: 'yes', label: 'Yes — I\'ve checked and I meet them (or none required)' },
          { value: 'checking', label: 'I\'m still checking' },
          { value: 'no', label: 'No — I haven\'t checked' },
        ],
        required: true,
      },
    ],
  },
  {
    id: 'erasmus-documents',
    title: 'Document Readiness',
    estimatedMinutes: 2,
    questions: [
      {
        id: 'erasmus-doc-1',
        type: 'checklist',
        text: 'Which of the following documents do you have ready?',
        section: 'documents',
        sectionIndex: 5,
        helpText: 'Each programme may have additional requirements. These are the most common documents needed.',
        checklistItems: [
          'CV in professional format (Europass or academic CV)',
          'Academic transcripts with certified translations (if not in English)',
          'Two reference letters from academic or professional referees',
          'Tailored motivation letter for each programme you are applying to',
          'Copy of Bachelor\'s degree certificate',
          'Valid passport',
        ],
        required: true,
      },
    ],
  },
];

// ── Chevening Track ──
const CHEVENING_QUESTIONS: QuestionSection[] = [
  {
    id: 'chev-eligibility',
    title: 'Eligibility',
    estimatedMinutes: 3,
    questions: [
      {
        id: 'chev-gate-1',
        type: 'gate',
        text: 'Are you a citizen of a Chevening-eligible country?',
        section: 'eligibility',
        sectionIndex: 0,
        helpText: 'Chevening covers 160+ countries and territories. Most developing countries are eligible.',
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
        ],
        gateFailMessage: 'Chevening is only open to citizens of eligible countries. Check the Chevening website for the full list.',
        gateRecommendedTrack: 'erasmus',
        required: true,
      },
      {
        id: 'chev-gate-2',
        type: 'gate',
        text: 'Do you confirm that you do NOT hold UK citizenship or have indefinite leave to remain in the UK?',
        section: 'eligibility',
        sectionIndex: 0,
        helpText: 'UK citizens and permanent residents are not eligible for Chevening.',
        options: [
          { value: 'yes', label: 'Correct — I am NOT a UK citizen/resident' },
          { value: 'no', label: 'I am a UK citizen or permanent resident' },
        ],
        gateFailMessage: 'UK citizens and permanent residents are not eligible for Chevening scholarships.',
        required: true,
      },
      {
        id: 'chev-gate-3',
        type: 'gate',
        text: 'Did you complete your undergraduate degree before October 2023?',
        section: 'eligibility',
        sectionIndex: 0,
        helpText: 'You must have completed your undergraduate degree before the academic year starts. Fresh graduates from October 2023 onwards may not be eligible for the current cycle.',
        options: [
          { value: 'yes', label: 'Yes — I graduated before October 2023' },
          { value: 'no', label: 'No — I graduated after October 2023' },
        ],
        gateFailMessage: 'Chevening requires an undergraduate degree completed before the current cycle start. You may need to wait for a future cycle.',
        required: true,
      },
      {
        id: 'chev-gate-4',
        type: 'gate',
        text: 'Do you have an undergraduate degree equivalent to a UK 2:1 (upper second class) or higher?',
        section: 'eligibility',
        sectionIndex: 0,
        helpText: 'Chevening requires at least a 2:1 or equivalent. For Nigerian universities: GPA ≥ 3.5/5.0 or ≥ 3.0/4.0.',
        options: [
          { value: 'yes', label: 'Yes — 2:1 or higher (or equivalent)' },
          { value: 'borderline', label: 'I have a 2:2 but strong work experience' },
          { value: 'no', label: 'No — below 2:2' },
        ],
        gateFailMessage: 'Chevening requires at least a 2:1 degree or equivalent. A strong 2:2 with exceptional work experience may occasionally be considered, but this is rare.',
        required: true,
      },
      {
        id: 'chev-gate-5',
        type: 'gate',
        text: 'Are you willing to return to your home country for at least 2 years after completing your studies?',
        section: 'eligibility',
        sectionIndex: 0,
        helpText: 'This is a binding condition of the Chevening scholarship. You must return to your country for a minimum of 2 years.',
        options: [
          { value: 'yes', label: 'Yes — I will return' },
          { value: 'no', label: 'No' },
        ],
        gateFailMessage: 'Chevening requires scholars to return to their home country for at least 2 years. This is non-negotiable.',
        required: true,
      },
    ],
  },
  {
    id: 'chev-experience',
    title: 'Work Experience',
    estimatedMinutes: 5,
    questions: [
      {
        id: 'chev-exp-1',
        type: 'calculator',
        text: 'Use the work experience calculator to add your employment periods. Chevening requires a minimum of 2,800 hours of work experience.',
        section: 'experience',
        sectionIndex: 1,
        helpText: 'Add each employment period separately. Include full-time, part-time, voluntary, and self-employed work. Hours worked during your undergraduate degree will be flagged but still counted. The calculator will total your hours automatically.',
        required: true,
      },
      {
        id: 'chev-exp-2',
        type: 'objective',
        text: 'Did any of your work experience occur during your undergraduate studies?',
        section: 'experience',
        sectionIndex: 1,
        helpText: 'Work during undergrad still counts towards the 2,800 hours, but Chevening evaluators may weigh post-graduation experience more heavily.',
        options: [
          { value: 'none', label: 'No — all my experience is after graduation' },
          { value: 'some', label: 'Some — but mostly after graduation' },
          { value: 'most', label: 'Most of my experience was during undergrad' },
        ],
        required: true,
      },
    ],
  },
  {
    id: 'chev-academic',
    title: 'Academic Background',
    estimatedMinutes: 2,
    questions: [
      {
        id: 'chev-acad-1',
        type: 'objective',
        text: 'What is your undergraduate degree classification?',
        section: 'academic',
        sectionIndex: 2,
        helpText: 'Chevening looks for at least a 2:1 or equivalent. First Class / Distinction strengthens your application.',
        options: [
          { value: 'first', label: 'First Class / Distinction' },
          { value: '2-1', label: 'Second Class Upper (2:1)' },
          { value: '2-2', label: 'Second Class Lower (2:2)' },
          { value: 'third', label: 'Third Class or below' },
        ],
        required: true,
      },
      {
        id: 'chev-acad-2',
        type: 'objective',
        text: 'Do you have any additional qualifications (Masters degree, professional certifications, etc.)?',
        section: 'academic',
        sectionIndex: 2,
        helpText: 'Additional qualifications can strengthen your application, though they are not required.',
        options: [
          { value: 'masters', label: 'Yes — I have a Masters degree' },
          { value: 'professional', label: 'Yes — professional certifications (CPA, PMP, etc.)' },
          { value: 'both', label: 'Both Masters and professional certifications' },
          { value: 'none', label: 'No additional qualifications' },
        ],
        required: true,
      },
    ],
  },
  {
    id: 'chev-leadership',
    title: 'Leadership and Influence',
    estimatedMinutes: 8,
    questions: [
      {
        id: 'chev-lead-1',
        type: 'self-score-text',
        text: 'Describe a specific situation where you demonstrated leadership. What was the challenge, what did you do, and what were the measurable results?',
        section: 'leadership',
        sectionIndex: 3,
        helpText: 'Chevening is a LEADERSHIP scholarship, not an academic one. Use the STAR format: Situation, Task, Action, Result. Include specific numbers and outcomes.',
        minWords: 80,
        maxWords: 300,
        required: true,
      },
      {
        id: 'chev-lead-2',
        type: 'self-score-text',
        text: 'Give an example of how you have built professional networks or relationships to achieve a goal. How did you influence others?',
        section: 'leadership',
        sectionIndex: 3,
        helpText: 'Chevening values networking and influence. Show how you have used relationships strategically — not just that you know people.',
        minWords: 80,
        maxWords: 300,
        required: true,
      },
    ],
  },
  {
    id: 'chev-career',
    title: 'Career Plan',
    estimatedMinutes: 5,
    questions: [
      {
        id: 'chev-career-1',
        type: 'self-score-text',
        text: 'Describe your 5-year career plan. How does a UK Masters degree specifically bridge the gap between where you are now and where you want to be?',
        section: 'career',
        sectionIndex: 4,
        helpText: 'Be specific about your current position, target role in 5 years, and exactly how the UK Masters fills the gap. Vague career plans are a common weakness.',
        minWords: 80,
        maxWords: 300,
        required: true,
      },
    ],
  },
  {
    id: 'chev-university',
    title: 'University Readiness',
    estimatedMinutes: 3,
    questions: [
      {
        id: 'chev-uni-1',
        type: 'objective',
        text: 'Have you identified 3 UK university courses you want to apply to?',
        section: 'university',
        sectionIndex: 5,
        helpText: 'Chevening requires you to list 3 university course choices in your application. All must be eligible one-year taught Masters programmes at UK universities.',
        options: [
          { value: '3', label: 'Yes — I have 3 courses selected' },
          { value: '1-2', label: 'I have 1–2 but need more' },
          { value: '0', label: 'Not yet' },
        ],
        required: true,
      },
      {
        id: 'chev-uni-2',
        type: 'objective',
        text: 'Have you checked the English language requirements for your chosen courses?',
        section: 'university',
        sectionIndex: 5,
        helpText: 'Each university sets its own language requirements. Most require IELTS 6.5–7.0 overall with no band below 6.0.',
        options: [
          { value: 'yes', label: 'Yes — I meet the requirements' },
          { value: 'checking', label: 'I\'m checking / preparing' },
          { value: 'no', label: 'No — I haven\'t checked' },
        ],
        required: true,
      },
      {
        id: 'chev-uni-3',
        type: 'objective',
        text: 'Are you aware that the Chevening application typically opens in August and closes in early November, with interviews around April–May?',
        section: 'university',
        sectionIndex: 5,
        helpText: 'The July conditional offer deadline means you should secure university offers before or shortly after submitting Chevening. Plan accordingly.',
        options: [
          { value: 'yes', label: 'Yes — I have the timeline mapped' },
          { value: 'vaguely', label: 'I know roughly but not the details' },
          { value: 'no', label: 'No — this is new to me' },
        ],
        required: true,
      },
    ],
  },
  {
    id: 'chev-documents',
    title: 'Document Readiness',
    estimatedMinutes: 2,
    questions: [
      {
        id: 'chev-doc-1',
        type: 'checklist',
        text: 'Which of the following documents do you have ready?',
        section: 'documents',
        sectionIndex: 6,
        helpText: 'Chevening requires 4 essay responses (leadership, networking, career plan, and study in the UK). Start drafting early.',
        checklistItems: [
          'Updated CV with dates and descriptions for all roles',
          'Two references identified (one professional, one academic/character)',
          'Draft personal statement for Chevening Essay 1: Leadership and Influence',
          'Draft personal statement for Chevening Essay 2: Networking',
          'Draft personal statement for Chevening Essay 3: Career Plan',
          'Draft personal statement for Chevening Essay 4: Studying in the UK',
        ],
        required: true,
      },
    ],
  },
];

// ── Fulbright Track ──
const FULBRIGHT_QUESTIONS: QuestionSection[] = [
  {
    id: 'ful-eligibility',
    title: 'Country Routing & Eligibility',
    estimatedMinutes: 3,
    questions: [
      {
        id: 'ful-route-1',
        type: 'country-route',
        text: 'Which country are you applying from? This determines your Fulbright track (FFSP, Open Study Award, or Standard).',
        section: 'eligibility',
        sectionIndex: 0,
        helpText: 'Different countries have different Fulbright programmes. Nigeria has FFSP (PhD/Faculty) and Open Study Award (Masters). Other countries may have standard Masters/PhD tracks.',
        required: true,
      },
      {
        id: 'ful-gate-1',
        type: 'gate',
        text: 'Do you confirm that you are NOT a US citizen or permanent resident?',
        section: 'eligibility',
        sectionIndex: 0,
        helpText: 'Fulbright Foreign Student Program is for non-US citizens only.',
        options: [
          { value: 'yes', label: 'Correct — I am NOT a US citizen/resident' },
          { value: 'no', label: 'I am a US citizen or permanent resident' },
        ],
        gateFailMessage: 'The Fulbright Foreign Student Program is for non-US citizens. US citizens should look into the Fulbright U.S. Student Program instead.',
        required: true,
      },
      {
        id: 'ful-gate-2',
        type: 'gate',
        text: 'Have you previously received a Fulbright scholarship?',
        section: 'eligibility',
        sectionIndex: 0,
        helpText: 'In most countries, previous Fulbright scholars are not eligible for a second award.',
        options: [
          { value: 'no', label: 'No — this would be my first Fulbright' },
          { value: 'yes', label: 'Yes — I have received a Fulbright before' },
        ],
        gateFailMessage: 'Previous Fulbright recipients are generally not eligible for a second award. Check with your country\'s Fulbright Commission for exceptions.',
        gateRecommendedTrack: 'chevening',
        required: true,
      },
      {
        id: 'ful-elig-3',
        type: 'objective',
        text: 'Have you spent significant time (6+ months) in the United States in the last 3 years?',
        section: 'eligibility',
        sectionIndex: 0,
        helpText: 'This is NOT a hard disqualifier, but extended recent US experience may reduce the perceived need for cultural exchange, which is central to Fulbright\'s mission. Brief visits and conferences are fine.',
        options: [
          { value: 'no', label: 'No — no extended US stays' },
          { value: 'short', label: 'Yes — but less than 12 months total' },
          { value: 'extended', label: 'Yes — 12+ months in the US' },
        ],
        required: true,
      },
    ],
  },
  {
    id: 'ful-academic',
    title: 'Academic Excellence',
    estimatedMinutes: 3,
    questions: [
      {
        id: 'ful-acad-1',
        type: 'objective',
        text: 'What is your undergraduate GPA or degree classification?',
        section: 'academic',
        sectionIndex: 1,
        helpText: 'Fulbright is academically competitive. A GPA of 3.0+/4.0 (or 3.5+/5.0, or 2:1) is generally expected.',
        options: [
          { value: 'first', label: 'First Class / 3.7+ GPA (4.0 scale) / 4.5+ (5.0 scale)' },
          { value: '2-1', label: '2:1 / 3.0–3.69 GPA (4.0) / 3.5–4.49 (5.0)' },
          { value: '2-2', label: '2:2 / 2.5–2.99 GPA (4.0) / 3.0–3.49 (5.0)' },
          { value: 'third', label: 'Third Class or below' },
        ],
        required: true,
      },
      {
        id: 'ful-acad-2',
        type: 'objective',
        text: 'Do you have publications, conference presentations, or significant research experience?',
        section: 'academic',
        sectionIndex: 1,
        helpText: 'Research output demonstrates academic maturity. For PhD-track applicants, this is especially important.',
        options: [
          { value: 'publications', label: 'Yes — published papers or book chapters' },
          { value: 'conferences', label: 'Conference presentations or posters' },
          { value: 'research', label: 'Research experience but no publications' },
          { value: 'none', label: 'No research experience' },
        ],
        required: true,
      },
      {
        id: 'ful-acad-3',
        type: 'objective',
        text: 'For Nigeria FFSP applicants: Are you currently enrolled in a PhD programme with 2+ years completed?',
        section: 'academic',
        sectionIndex: 1,
        helpText: 'The Nigeria FFSP track targets PhD students who have completed at least 2 years. Masters applicants should use the Open Study Award track.',
        options: [
          { value: 'yes', label: 'Yes — 2+ years into PhD' },
          { value: 'starting', label: 'Just starting PhD' },
          { value: 'masters', label: 'I\'m applying for Masters, not PhD' },
          { value: 'na', label: 'Not applying through Nigeria FFSP' },
        ],
        required: true,
      },
    ],
  },
  {
    id: 'ful-research',
    title: 'Research Proposal',
    estimatedMinutes: 8,
    questions: [
      {
        id: 'ful-res-1',
        type: 'self-score-text',
        text: 'Describe your research question, methodology, and why the United States is the best place to pursue this research. What specific universities, labs, or professors have you identified?',
        section: 'research',
        sectionIndex: 2,
        helpText: 'The research proposal is the MOST critical element of a Fulbright application. It must be original — Fulbright has ZERO tolerance for plagiarism. Be specific about your methodology and why US resources are essential.',
        minWords: 80,
        maxWords: 300,
        required: true,
      },
      {
        id: 'ful-res-2',
        type: 'self-score-text',
        text: 'How does your academic and professional background prepare you for this research? What will you bring back to your home country?',
        section: 'research',
        sectionIndex: 2,
        helpText: 'Show the connection between your past, your proposed research, and your future impact. Fulbright is about cultural exchange and mutual benefit.',
        minWords: 80,
        maxWords: 300,
        required: true,
      },
    ],
  },
  {
    id: 'ful-language',
    title: 'Language Readiness',
    estimatedMinutes: 2,
    questions: [
      {
        id: 'ful-lang-1',
        type: 'objective',
        text: 'What is your TOEFL score (or equivalent)?',
        section: 'language',
        sectionIndex: 3,
        helpText: 'Nigeria FFSP requires a minimum TOEFL score of 90. The US Embassy may cover TOEFL costs for Fulbright applicants — check with your country\'s Fulbright Commission.',
        options: [
          { value: '100+', label: 'TOEFL 100+ / IELTS 7.0+' },
          { value: '90-99', label: 'TOEFL 90–99 / IELTS 6.5' },
          { value: '80-89', label: 'TOEFL 80–89 / IELTS 6.0' },
          { value: 'below-80', label: 'Below TOEFL 80' },
          { value: 'none', label: 'No score yet (Embassy may cover costs)' },
        ],
        required: true,
      },
      {
        id: 'ful-lang-2',
        type: 'objective',
        text: 'Are you aware that the US Embassy may cover your TOEFL registration costs as part of the Fulbright application process?',
        section: 'language',
        sectionIndex: 3,
        helpText: 'In many countries, the Fulbright Commission or US Embassy pays for your TOEFL test. Confirm with your local commission before paying out of pocket.',
        options: [
          { value: 'yes', label: 'Yes — I know about this' },
          { value: 'no', label: 'No — this is new information' },
        ],
        required: true,
      },
    ],
  },
  {
    id: 'ful-priority',
    title: 'Priority Field Alignment',
    estimatedMinutes: 1,
    questions: [
      {
        id: 'ful-pri-1',
        type: 'objective',
        text: 'Does your field of study align with Fulbright priority areas? (AI, Conflict Negotiation, Cybersecurity, Disease Prevention, Health Digitalisation, STEM, Supply Chain Management, Trade)',
        section: 'priority',
        sectionIndex: 4,
        helpText: 'Priority fields receive extra attention, but non-priority fields are still funded. Alignment helps but is not required.',
        options: [
          { value: 'direct', label: 'Yes — directly in a priority area' },
          { value: 'related', label: 'Related to a priority area' },
          { value: 'no', label: 'No — different field (still eligible)' },
        ],
        required: true,
      },
    ],
  },
  {
    id: 'ful-documents',
    title: 'Document Readiness',
    estimatedMinutes: 2,
    questions: [
      {
        id: 'ful-doc-1',
        type: 'checklist',
        text: 'Which of the following documents do you have ready?',
        section: 'documents',
        sectionIndex: 5,
        helpText: 'The research proposal must be 100% original. Fulbright uses plagiarism detection software and has zero tolerance for any copied content.',
        checklistItems: [
          'Research proposal drafted (original work — zero plagiarism tolerance)',
          'Three recommendation letters (at least one academic)',
          'Official academic transcripts from all institutions attended',
          'CV / Resume (US format preferred)',
          'TOEFL score report (or test date scheduled)',
          'Study objectives / personal statement drafted',
        ],
        required: true,
      },
    ],
  },
];

// ── Export combined question bank ──
export const TRACK_QUESTIONS: Record<TrackId, QuestionSection[]> = {
  'helmut-schmidt': HELMUT_SCHMIDT_QUESTIONS,
  'epos': EPOS_QUESTIONS,
  'erasmus': ERASMUS_QUESTIONS,
  'chevening': CHEVENING_QUESTIONS,
  'fulbright': FULBRIGHT_QUESTIONS,
};

/** Flatten all questions for a track into a single array */
export function getAllQuestionsForTrack(track: TrackId): import('./types').Question[] {
  return TRACK_QUESTIONS[track].flatMap(section => section.questions);
}

/** Get a specific question by ID across all tracks */
export function getQuestionById(questionId: string): import('./types').Question | undefined {
  for (const track of Object.values(TRACK_QUESTIONS)) {
    for (const section of track) {
      const q = section.questions.find(q => q.id === questionId);
      if (q) return q;
    }
  }
  return undefined;
}
