import React from 'react';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Does ChatGPT Content Fail Turnitin? | Cee Writing Blog',
  description: 'Find out whether AI-generated content from ChatGPT actually gets flagged by Turnitin AI detection, and what you can do about it.',
};

export default function BlogPost() {
  return (
    <main>
      <Navbar />

      {/* Article Header */}
      <section className="gradient-mesh" style={{
        background: 'linear-gradient(160deg, #061428, #0B1F3A, #112d52)',
        paddingTop: '140px', paddingBottom: '80px',
        position: 'relative', overflow: 'hidden',
      }}>
        <div className="orb orb-1" />
        <div style={{position: 'relative', zIndex: 2, maxWidth: '800px', margin: '0 auto', padding: '0 24px'}}>
          <Link href="/blog" style={{
            display: 'inline-flex', alignItems: 'center', gap: '6px',
            color: 'rgba(255,255,255,0.4)', fontSize: '13px', textDecoration: 'none',
            marginBottom: '24px', transition: 'color 0.2s',
          }}>
            ← Back to Blog
          </Link>

          <div style={{
            display: 'inline-block', background: 'rgba(201,147,58,0.15)',
            border: '1px solid rgba(201,147,58,0.3)',
            color: '#E8B96A', fontSize: '11px', fontWeight: 700, letterSpacing: '2px',
            textTransform: 'uppercase', padding: '5px 14px', borderRadius: '50px',
            marginBottom: '20px', marginLeft: '12px',
          }}>
            AI Detection
          </div>

          <h1 style={{
            fontFamily: "'Playfair Display', serif", fontSize: 'clamp(28px, 5vw, 48px)',
            fontWeight: 900, color: 'white', lineHeight: 1.15, marginBottom: '20px',
          }}>
            Does ChatGPT Content Fail Turnitin? Here is The Truth
          </h1>

          <div style={{
            display: 'flex', alignItems: 'center', gap: '16px',
            fontSize: '13px', color: 'rgba(255,255,255,0.4)',
          }}>
            <span>March 10, 2026</span>
            <span style={{width: '4px', height: '4px', borderRadius: '50%', background: 'rgba(255,255,255,0.2)'}} />
            <span>5 min read</span>
          </div>
        </div>

        <div style={{position: 'absolute', bottom: '-1px', left: 0, right: 0, zIndex: 3}}>
          <svg viewBox="0 0 1440 60" fill="none" xmlns="http://www.w3.org/2000/svg" style={{display: 'block', width: '100%'}}>
            <path d="M0,30 C360,60 720,0 1080,30 C1260,50 1380,40 1440,30 L1440,60 L0,60Z" fill="#FDFAF5"/>
          </svg>
        </div>
      </section>

      {/* Article Body */}
      <article style={{
        background: 'var(--cream)', padding: '60px 24px 100px',
      }}>
        <div style={{maxWidth: '720px', margin: '0 auto'}}>
          <p style={{fontSize: '17px', color: 'var(--text)', lineHeight: 1.85, marginBottom: '24px'}}>
            It is the question on every student&apos;s mind right now: &ldquo;If I use ChatGPT to write my assignment, will Turnitin catch me?&rdquo;
          </p>
          <p style={{fontSize: '17px', color: 'var(--text)', lineHeight: 1.85, marginBottom: '24px'}}>
            The short answer is <strong>yes, very likely</strong>. Turnitin now includes an AI detection feature that can identify content generated by large language models like GPT-4 with high accuracy. But the full picture is more nuanced than that.
          </p>

          <h2 style={{
            fontFamily: "'Playfair Display', serif", fontSize: '24px',
            fontWeight: 700, color: 'var(--navy)', marginTop: '40px', marginBottom: '16px',
          }}>
            How Does Turnitin AI Detection Work?
          </h2>
          <p style={{fontSize: '17px', color: 'var(--text)', lineHeight: 1.85, marginBottom: '24px'}}>
            Turnitin analyzes the patterns in your text. AI-generated writing tends to have a certain predictability in word choice, sentence length, and transitions that human writing does not. The system assigns an AI score showing what percentage of the document it believes was AI-generated.
          </p>

          {/* Callout Box */}
          <div style={{
            background: 'var(--white)', borderLeft: '4px solid var(--gold)',
            borderRadius: '0 12px 12px 0', padding: '20px 24px', marginBottom: '28px',
            boxShadow: 'var(--clay-shadow)',
          }}>
            <p style={{fontSize: '15px', color: 'var(--navy)', lineHeight: 1.7, fontWeight: 500}}>
              Important: A high AI score does not automatically mean you &ldquo;cheated.&rdquo; But most institutions will investigate further if the score is above 20%.
            </p>
          </div>

          <h2 style={{
            fontFamily: "'Playfair Display', serif", fontSize: '24px',
            fontWeight: 700, color: 'var(--navy)', marginTop: '40px', marginBottom: '16px',
          }}>
            What Can You Do About It?
          </h2>
          <p style={{fontSize: '17px', color: 'var(--text)', lineHeight: 1.85, marginBottom: '16px'}}>
            If you have used AI to help draft your work and want to make sure it reads naturally and passes detection, here is what we recommend:
          </p>
          <ol style={{paddingLeft: '20px', marginBottom: '24px'}}>
            {[
              'Rewrite the content in your own voice and style.',
              'Add personal examples, experiences, and specific references.',
              'Vary your sentence structure and use natural transitions.',
              'Or use our AI Humanizing Service, where we professionally rewrite AI content so it passes any AI detector.',
            ].map((item, i) => (
              <li key={i} style={{
                fontSize: '16px', color: 'var(--text)', lineHeight: 1.8,
                marginBottom: '10px', paddingLeft: '8px',
              }}>
                {item}
              </li>
            ))}
          </ol>

          <h2 style={{
            fontFamily: "'Playfair Display', serif", fontSize: '24px',
            fontWeight: 700, color: 'var(--navy)', marginTop: '40px', marginBottom: '16px',
          }}>
            The Bottom Line
          </h2>
          <p style={{fontSize: '17px', color: 'var(--text)', lineHeight: 1.85, marginBottom: '40px'}}>
            AI tools are useful, but submitting raw AI content is risky. The safest approach is to use AI as a starting point and then humanize or rewrite the content. That is exactly what our AI Humanizing Service does: we take AI-generated text and make it genuinely human, while keeping your original meaning intact.
          </p>

          {/* Author CTA */}
          <div style={{
            background: 'linear-gradient(135deg, var(--navy), var(--navy-mid))',
            borderRadius: '20px', padding: '36px 32px',
            display: 'flex', alignItems: 'center', justifyContent: 'space-between',
            flexWrap: 'wrap', gap: '20px',
          }}>
            <div>
              <div style={{fontSize: '12px', color: 'rgba(255,255,255,0.4)', letterSpacing: '2px', textTransform: 'uppercase', marginBottom: '6px'}}>Need Help?</div>
              <div style={{fontFamily: "'Playfair Display', serif", fontSize: '20px', fontWeight: 700, color: 'white'}}>
                Worried about AI detection? We can help.
              </div>
            </div>
            <a href="https://wa.me/234XXXXXXXXXX" target="_blank" rel="noreferrer" className="btn-gold" style={{flexShrink: 0}}>
              <span>Get AI Humanizing</span>
            </a>
          </div>
        </div>
      </article>

      <Footer />
    </main>
  );
}
